""" Billing config values. """

BILLING_AUTH = "BILLING_AUTH"
BASE_URL = "/billing/v1"
CARDS_URL = BASE_URL + "/cards"
CLOUD_COSTS_URL = BASE_URL + "/cloud-costs"
DIRECT_DEBIT_URL = BASE_URL + "/direct-debit"
INVOICE_QUERIES_URL = BASE_URL + "/invoice-queries"
INVOICE_URL = BASE_URL + "/invoices"
PAYMENTS_URL = BASE_URL + "/payments"
RECURRING_COSTS_URL = BASE_URL + "/recurring-costs"
