echo Running BUILD container...
./run_build_test.sh

echo Running LINT container...
./run_pylint_test.sh

echo Running TEST container...
./run_pytest_test.sh

echo Running DOCS container...
./run_docs_test.sh