name: Deploy Package
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Pip Installs
        run: |
          pip install -r requirements_ci.txt

      - name: Get Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Package Wheel
        run: |
          echo ${{ env.RELEASE_VERSION }} > VERSION
          python setup.py bdist_wheel
      
      - name: Deploy Package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI }}
        run: |
          python -m twine upload dist/*